export type Direction = 'adverse' | 'favourable' | 'neutral';

export interface Company {
  code: string;
  name: string;
}

export interface BusinessUnit {
  code: string;
  label: string;
  companies: Company[];
}

export interface KpiCard {
  id: string;
  label: string;
  value: string;
  delta?: string;
  direction?: Direction;
  highlighted?: boolean;
  nodeId?: string;
  trend?: number[];
}

export type OperationalUnit = 'usd-per-day' | 'usd-per-month' | 'percent' | 'days' | 'count';

/**
 * One row of the Financial Performance statement table, generated by walking
 * the GL/FSI tree (see gl-client.ts) rather than hand-authored — indent tracks
 * real hierarchy depth, not just 0/1. Values already carry the right sign
 * (see docs/adr/0023), so there's no separate `sign` field to render parens.
 */
export interface DisplayRow {
  nodeId: string;
  label: string;
  indent: number;
  isSubtotal?: boolean;
  isFinal?: boolean;
  /** nodeId of the collapsible group this row belongs to, if nested under one. */
  group?: string;
  /** Operational value driver (rate/utilization/off-hire days, etc.) rather than a GL amount in RM millions. */
  kind?: 'operational';
  unit?: OperationalUnit;
}

export interface BridgeStep {
  label: string;
  value: number;
  kind: 'total' | 'increase' | 'decrease';
}

export interface MonthlySeries {
  label: string;
  values: number[];
}

export interface ContributionDriver {
  id: string;
  label: string;
  varAbs: number;
  varPct: number;
  direction: Direction;
  rank: number;
}

export interface Sensitivity {
  mostSensitive: string[];
  mostVariable: string[];
}

export interface BenchmarkBar {
  id: string;
  label: string;
  valuePerVod: number;
  kind: 'subject' | 'internal' | 'external';
}

export interface BenchmarkRow {
  basis: string;
  valuePerVod: string;
  gap: string;
}

export interface Benchmark {
  metricLabel: string;
  basis: string;
  bars: BenchmarkBar[];
  rows: BenchmarkRow[];
}

export interface RootCauseEntry {
  id: string;
  driverLabel: string;
  amountLabel: string;
  type: 'FACT' | 'AI_HYPOTHESIS';
  evidenceOrRationale: string;
  mitigation?: string;
  status: 'Validated' | 'AI proposed' | 'Under review' | 'Rejected';
  confidence?: 'Low' | 'Medium' | 'High';
  analystNotes?: string;
}

export type GlNodeType = 'Reporting Root' | 'Reporting Node' | 'Posting GL Account' | 'Operational Driver';

/** A node in the real GL/FSI hierarchy served by GET /api/gl/tree — see docs/adr/0022. */
export interface VdtNode {
  id: string;
  name: string;
  parentId: string | null;
  childIds: string[];
  nodeType: GlNodeType;
  unit: 'RM_M' | OperationalUnit;
  actual: number;
  budget: number;
  priorYear: number;
  monthlyActual: number[];
  direction: Direction;
  hasFullData: boolean;
  trend?: number[];
  drivers?: ContributionDriver[];
  sensitivity?: Sensitivity;
  benchmark?: Benchmark;
  rootCause?: RootCauseEntry[];
  reviewSummary?: string;
}

/** A VdtNode ranked against its siblings by contribution to variance (see rankChildren in gl-client.ts). */
export interface RankedNode extends VdtNode {
  varAbs: number;
  rank: number;
  contributionWidthPct: number;
}

export interface DriverLink {
  label: string;
  amount: string;
  nodeId?: string;
}

export interface LeadingIndicator {
  label: string;
  value: string;
}

export interface Exception {
  title: string;
  impact: string;
  explainedPct: number;
  targetNodeId: string;
}
