export type Direction = 'adverse' | 'favourable' | 'neutral';

export type CompanyNodeType = 'Group' | 'Business Unit' | 'Company';

/** A node in the MISC Group -> Business Unit -> Company hierarchy served by GET /api/companies — see docs/adr/0028. */
export interface CompanyNode {
  id: string;
  label: string;
  companyType: CompanyNodeType;
  parentId: string | null;
  childIds: string[];
}

export interface KpiCard {
  id: string;
  label: string;
  value: string;
  delta?: string;
  direction?: Direction;
  highlighted?: boolean;
  nodeId?: string;
  trend?: number[];
  /** Tailwind fill classes for the trend bar chart, e.g. 'fill-red-600 dark:fill-red-400'. */
  trendFillClass?: string;
  /** Per-bar hover text for the trend bar chart, e.g. "Jan (Prior Year): RM188.9m". */
  trendTooltips?: string[];
}

export type OperationalUnit = 'usd-per-day' | 'usd-per-month' | 'percent' | 'days' | 'count' | 'ratio';

/**
 * One row of the Financial Performance statement table, generated by walking
 * the GL/FSI tree (see gl-client.ts) rather than hand-authored — indent tracks
 * real hierarchy depth, not just 0/1. Values already carry the right sign
 * (see docs/adr/0023), so there's no separate `sign` field to render parens.
 */
export interface DisplayRow {
  nodeId: string;
  label: string;
  indent: number;
  isSubtotal?: boolean;
  isFinal?: boolean;
  /** nodeId of the collapsible group this row belongs to, if nested under one. */
  group?: string;
  /** A Driver Formula or Driver row (see docs/adr/0030) rather than a plain GL statement row. */
  kind?: 'operational';
  /** Which half of the driver graph this row is — set only when kind is 'operational'. */
  driverNodeType?: 'formula' | 'driver';
  /** Sum-of-products expression text, set only on 'formula' rows. */
  expression?: string;
  unit?: OperationalUnit | 'RM_M';
}

export interface BridgeStep {
  label: string;
  value: number;
  kind: 'total' | 'increase' | 'decrease';
}

export interface MonthlySeries {
  label: string;
  values: number[];
}

export interface ContributionDriver {
  id: string;
  label: string;
  varAbs: number;
  varPct: number;
  direction: Direction;
  rank: number;
}

export interface Sensitivity {
  mostSensitive: string[];
  mostVariable: string[];
}

export interface BenchmarkBar {
  id: string;
  label: string;
  valuePerVod: number;
  kind: 'subject' | 'internal' | 'external';
}

export interface BenchmarkRow {
  basis: string;
  valuePerVod: string;
  gap: string;
}

export interface Benchmark {
  metricLabel: string;
  basis: string;
  bars: BenchmarkBar[];
  rows: BenchmarkRow[];
}

export interface RootCauseEntry {
  id: string;
  driverLabel: string;
  amountLabel: string;
  type: 'FACT' | 'AI_HYPOTHESIS';
  evidenceOrRationale: string;
  mitigation?: string;
  status: 'Validated' | 'AI proposed' | 'Under review' | 'Rejected';
  confidence?: 'Low' | 'Medium' | 'High';
  analystNotes?: string;
}

export type GlNodeType = 'Reporting Root' | 'Reporting Node' | 'Posting GL Account' | 'Driver Formula' | 'Driver';

/** A node in the real GL/FSI hierarchy served by GET /api/gl/tree — see docs/adr/0022. */
export interface VdtNode {
  id: string;
  name: string;
  parentId: string | null;
  childIds: string[];
  nodeType: GlNodeType;
  unit: 'RM_M' | OperationalUnit;
  actual: number;
  budget: number;
  priorYear: number;
  monthlyActual: number[];
  monthlyPriorYear: number[];
  direction: Direction;
  hasFullData: boolean;
  /** Sum-of-products expression text — only set on 'Driver Formula' nodes (see docs/adr/0030). */
  expression?: string;
  trend?: number[];
  drivers?: ContributionDriver[];
  sensitivity?: Sensitivity;
  benchmark?: Benchmark;
  rootCause?: RootCauseEntry[];
  reviewSummary?: string;
}

/** A VdtNode ranked against its siblings by contribution to variance (see rankChildren in gl-client.ts). */
export interface RankedNode extends VdtNode {
  varAbs: number;
  rank: number;
  contributionWidthPct: number;
}

export type PeriodType = 'Year' | 'Quarter' | 'Month';

/** A node in the Year/Quarter/Month hierarchy served by GET /api/periods — see docs/adr/0025. */
export interface PeriodNode {
  id: string;
  label: string;
  periodType: PeriodType;
  parentId: string | null;
  childIds: string[];
  order: number;
}

export interface DriverLink {
  label: string;
  amount: string;
  nodeId?: string;
}

export interface LeadingIndicator {
  label: string;
  value: string;
}

export interface Exception {
  title: string;
  impact: string;
  explainedPct: number;
  targetNodeId: string;
}
